### ISSUE TITLE
Suggestion to add more Details to the D-A-CH Support Bot Command §account

### ISSUE THREAD

**Issue by louis88-steemit** [jedigeiss/dach-support#12]
My suggestion refers to the extension of the Discord-Bot "D-A-CH Support" from @jedigeiss, which is currently to be implemented on our D-A-CH Discord Server with more than 1000 members. It is great to have such a large number of active users in the German community

----------

In the current status of the Discord Bot for the German community it is possible to display useful information about a user of the Steemit community via §account[steemitusername]. Further information could give you more detailed information about the user.

![dach support bot](https://i.imgur.com/UI3HYqP.png)

<sub> Picture shows Command Result: $account louis88 </sub>

My suggestion would be that you can display more information about an account such as:

- The reputation of the user - example: (Reputation: 53)
- The age of the user account at Steemit - example: (x days old)
- That the username is linked to the Steemit profile

----------

Information such as the name, the Steempower, the number of available SBD and STEEM and the current voting power are currently displayed.

By getting more information about a Steemituser you get a better overview of the current situation of the user. Displaying additional values promotes the information that can be obtained by the bot at a single collected location.
    

----------

**Comment by jedigeiss** [comment]
done with the last update! thanks for the ideas!
