### ISSUE TITLE
Suggestion for further information in the D-A-CH Support Bot to display the Steempower and further details

### ISSUE THREAD

**Issue by louis88-steemit** [jedigeiss/dach-support#14]
In my opinion, the bot could have some more great features and display more information about the user. For example, the more detailed display of Steem Power or the number of days of the registered user.
I made a screenshot of how I would like to see the changes and the output by the bot

Bot Command is: `?info louis88`

![account-infos](https://i.imgur.com/WxWfXGz.jpg)

**And here the single information from the picture explains**

 1. Shows the actual available Steempower of the user he has available for voting
 2. Displays the Steem Power that he has delegated to other Steemit users
 3. Shows the Steempower to which the Steemit user has been delegated by other Steemit users which increases the total Steempower.
 4. Describes the number of Steem that the user has saved in his Savings. Furthermore the display of the SBD a user has in his Savings. This is shown in brackets behind the display of Available Steem and SBD.
 5. Besides displaying when a user account was created, it would be great if the display was extended to show the number of days.

The further display of information provides an even better overview of the current status of a Steemit user and his information on the platform

**Comment by jedigeiss** [comment]
done with the latest update, thanks for the ideas!
